MVCBlog/Controllers/KategoriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCBlog.Models;

namespace MVCBlog.Controllers
{
    public class KategoriController : Controller
    {
        public BlogContext db = new BlogContext();



        public PartialViewResult KategoriListesi()
        {
            return PartialView(db.Kategoris.ToList());
        }

        public PartialViewResult Kategoriler()
        {
            return PartialView(db.Kategoris.ToList());
        }
        // GET: Kategori
        public ActionResult Index()
        {
            return View();
        }

        // GET: Kategori/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Kategori/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Kategori/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Kategori/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Kategori/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Kategori/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Kategori/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

MVCBlog/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVCBlog.Models;

namespace MVCBlog.Controllers
{
    public class PostController : Controller
    {
        private BlogContext db = new BlogContext();

        public ActionResult List(int? id, Kullanici model)
        {
            var postlar = db.Posts
                .Select(i => new Class1()
                {
                    Id = i.Id,
                    Baslik = i.Baslik,
                    Aciklama = i.Aciklama,
                    Resim = i.Resim,
                    EklenmeTarihi = i.EklenmeTarihi,
                    KullaniciId = i.KullaniciId,  
                    KullaniciAd=i.Kullanici.KullaniciAd,

                    KategoriId = i.KategoriId

                }).AsQueryable();
            if (id != null)
            {
                postlar = postlar.Where(i => i.KategoriId == id);
            }

            return View(postlar.ToList());
        }

        // GET: Post
        public ActionResult Index(int? id)
        {
            ViewBag.KategoriId = db.Kategoris.ToList();
            var postlar = db.Posts.OrderByDescending(x => x.Id).ToList();   
            return View(postlar);
        }

        public ActionResult Yazilarim()
        {
            var kullaniciadi = Session["username"].ToString();
            var postlar = db.Kullanicis.Where(a => a.KullaniciAd == kullaniciadi).SingleOrDefault().Posts.ToList();
            return View(postlar);
        }

        // GET: Post/Details/5
        public ActionResult Details(int? id)
        {
            var post = db.Posts.Where(i => i.Id == id).SingleOrDefault();
            return View(post);

        }

        // GET: Post/Create
        public ActionResult Create()
        {
            ViewBag.KategoriId = new SelectList(db.Kategoris, "Id", "KategoriAd");
            return View();
        }

        // POST: Post/Create
        [HttpPost]   
        public ActionResult Create(Post model)
        {
            try
            {
                if (Request.Files.Count>0)
                {
                    string dosyaadi = Path.GetFileName(Request.Files[0].FileName);
                    string uzanti = Path.GetExtension(Request.Files[0].FileName);
                    string yol = "~/Resimler/" + dosyaadi + uzanti;
                    Request.Files[0].SaveAs(Server.MapPath(yol));
                    model.Resim = "/Resimler/" + dosyaadi + uzanti;
                    
                }
                string kullaniciAdi = Session["username"].ToString();
                var kullanici = db.Kullanicis.Where(i => i.KullaniciAd == kullaniciAdi).SingleOrDefault();
                model.KullaniciId = kullanici.Id;
                model.EklenmeTarihi = DateTime.Now;
                db.Posts.Add(model);
                db.SaveChanges();
                return RedirectToAction("Index", "Kullanici");

            }
            catch 
            {      
                return View();
            }                   
        }

        // GET: Post/Edit/5
        public ActionResult Edit(int id)
        {
            string kullaniciadi = Session["username"].ToString();
            var post = db.Posts.Where(i => i.Id == id).SingleOrDefault();
            if (post==null)
            {
               return HttpNotFound();
            }
            if (post.Kullanici.KullaniciAd==kullaniciadi)
            {
                ViewBag.KategoriId = new SelectList(db.Kategoris, "Id", "KategoriAd");
                return View(post);
            }
            return HttpNotFound();
        }

        // POST: Post/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]  
        public ActionResult Edit(int id, Post model, HttpPostedFileBase resim)
        {
            try
            {
                if (Request.Files.Count > 0)
                {
                    string dosyaadi = Path.GetFileName(Request.Files[0].FileName);
                    string uzanti = Path.GetExtension(Request.Files[0].FileName);
                    string yol = "~/Resimler/" + dosyaadi + uzanti;
                    Request.Files[0].SaveAs(Server.MapPath(yol));
                    model.Resim = "/Resimler/" + dosyaadi + uzanti;

                }
                var post = db.Posts.Where(i => i.Id == id).SingleOrDefault();
                post.Baslik = model.Baslik;  
                post.Icerik = model.Icerik;
                post.Resim = model.Resim;
                post.KategoriId = model.KategoriId;
                db.SaveChanges();
                return RedirectToAction("Yazilarim");
            }
            catch
            {
                return View(model);
            }
        }

        // GET: Post/Delete/5
        public ActionResult Delete(int? id)
        {
            var kullaniciadi = Session["username"].ToString();
            var kullanici = db.Kullanicis.Where(i => i.KullaniciAd == kullaniciadi).SingleOrDefault();
            var post = db.Posts.Where(i => i.Id == id).SingleOrDefault();
            foreach(var i in post.Yorums.ToList())
            {
                db.Yorums.Remove(i);
                db.SaveChanges();
            }

            db.Posts.Remove(db.Posts.Find(id));
            db.SaveChanges();
            return RedirectToAction("Yazilarim");
        }
                       

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public JsonResult YorumYap(string yorum, int Postid)
        {

            var kullaniciadi = Session["username"].ToString();
            var kullanici = db.Kullanicis.Where(i => i.KullaniciAd == kullaniciadi).SingleOrDefault();



            db.Yorums.Add(new Yorum
            {
                KullaniciId = kullanici.Id,
                PostId = Postid,
                Yazi = yorum
            });
            db.SaveChanges();


            return Json(false, JsonRequestBehavior.AllowGet);

        }

        //[HttpGet]
        //public PartialViewResult YorumYap(int id)
        //{
        //    ViewBag.deger = id;
        //    return PartialView();
        //}

        //[HttpPost]
        //public PartialViewResult YorumYap(Yorum y)
        //{
        //    db.Yorums.Add(y);
        //    db.SaveChanges();
        //    return PartialView();
        //}
    }
}

MVCBlog/Views/Shared/_KullaniciLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <title>@ViewBag.Title - MVC Blog</title>
    <!-- Bootstrap core CSS -->
    <link href="~/Content/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <!-- <link href="assets\css\bootstrap.css" rel="stylesheet"> -->
    <!-- Additional CSS Files -->
    <link href="~/Content/assets/css/fontawesome.css" rel="stylesheet" />
    <link href="~/Content/assets/css/templatemo-stand-blog.css" rel="stylesheet" />
    <link href="~/Content/assets/css/owl.css" rel="stylesheet" />
    <link href="~/Content/assets/css/stillerim.css" rel="stylesheet" />
</head>
<body>
    <!-- ***** Preloader Start ***** -->
    <div id="preloader">
        <div class="jumper">
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>
   
    <header class="">
        <nav class="navbar navbar-expand-lg">
            <div class="container">
                <a class="navbar-brand" href="index.html"><h2>Papirüs<em>.</em></h2></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item active">
                            @Html.ActionLink("Ana Sayfa", "Index", "Post", new { area = "" }, new { @class = "nav-link" })
                        </li>

                        @{ Html.RenderAction("Kategoriler", "Kategori", new { @class = "nav-link" }); }

                        <li class="nav-item dropdown submenu">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" href="">İşlemler</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li class="nav-item nav-link">
                                    @Html.ActionLink("Yazı Oluştur", "Create", "Post", new { area = "" }, new { @class = "nav-link" })

                                    @Html.ActionLink("Yazılarım", "Yazilarim", "Post", new { area = "" }, new { @class = "nav-link" })
                                </li>
                            </ul>
                        </li>

                        <li class="nav-item dropdown submenu">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" href="">@Session["username"].ToString()</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li class="nav-item nav-link">
                                    @Html.ActionLink("Çıkış Yap", "CikisYap", "Kullanici", new { area = "" }, new { @class = "nav-link" })
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown submenu">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" href="index.html">TR</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li class="nav-item">
                                    <a class="nav-link" href="home-EN.html">EN</a>
                                </li>
                            </ul>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    @RenderBody()
    <footer>
        <div class="container">
            <div class="copyright-text">
                <p>
                    &copy; @DateTime.Now.Year - Sakarya MYO İnternet Programcılığı Dersi- Uygulama Projesi
                </p>
            </div>
            <div>
                <ul class="social-icons">
                    <li><a href="#" target="_blank"><i class="fa fa-facebook"></i></a></li>
                    <li><a href="#" target="_blank"><i class="fa fa-twitter"></i></a></li>
                    <li><a href="#" target="_blank"><i class="fa fa-linkedin"></i></a></li>
                    <li><a href="#" target="_blank"><i class="fa fa-youtube-play"></i></a></li>
                </ul>
            </div>
        </div>
    </footer>


    <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>
    @RenderSection("scripts", required: false)
    <!-- Bootstrap core JavaScript -->
    <script src="~/Content/vendor/jquery/jquery.min.js"></script>
    <script src="~/Content/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>


    <!-- Additional Scripts -->
    <script src="~/Content/assets/js/custom.js"></script>
    <script src="~/Content/assets/js/owl.js"></script>
    <script src="~/Content/assets/js/isotope.js"></script>
    <script src="~/Content/assets/js/slick.js"></script>
    <script src="~/Content/assets/js/accordions.js"></script>
    <script>
       $(document).ready(function () {
            $(window).scroll(function () {
                if ($(this).scrollTop() > 100) {
                    $('.back-to-top').fadeIn();
                } else {
                    $('.back-to-top').fadeOut();
                }
            });

            $('.back-to-top').click(function () {
                $("html, body").animate({
                    scrollTop: 0
                }, 600);
                return false;
            });

        });
    </script>

    <script language="text/Javascript">

      cleared[0] = cleared[1] = cleared[2] = 0; //set a cleared flag for each field
      function clearField(t){                   //declaring the array outside of the
      if(! cleared[t.id]){                      // function makes it static and global
          cleared[t.id] = 1;  // you could use true and false, but that's more typing
          t.value='';         // with more chance of typos
          t.style.color='#fff';
          }
      }
    </script>
</body>
</html>

MVCBlog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <title>@ViewBag.Title - MVC Blog</title>
    <!-- Bootstrap core CSS -->
    <link href="~/Content/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <!-- <link href="assets\css\bootstrap.css" rel="stylesheet"> -->
    <!-- Additional CSS Files -->
    <link href="~/Content/assets/css/fontawesome.css" rel="stylesheet" />
    <link href="~/Content/assets/css/templatemo-stand-blog.css" rel="stylesheet" />
    <link href="~/Content/assets/css/owl.css" rel="stylesheet" />
    <link href="~/Content/assets/css/stillerim.css" rel="stylesheet" />
</head>
<body>
    <!-- ***** Preloader Start ***** -->
    <div id="preloader">
        <div class="jumper">
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>

    <header class="">
        <nav class="navbar navbar-expand-lg">
            <div class="container">
                <a class="navbar-brand" href="/Home/Index"><h2>Papirüs<em>.</em></h2></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item active">
                            @if (Session["username"] == null)
                            {
                                <a class="nav-link" href="/Home/Index">
                                    Ana Sayfa
                                    <span class="sr-only">(current)</span>
                                </a>
                            }
                            else
                            {
                                @Html.ActionLink("Ana Sayfa", "Index", "Post", new { area = "" }, new { @class = "nav-link" })

                            }

                        </li>


                      
                       
                            @{ Html.RenderAction("Kategoriler", "Kategori", new { @class = "nav-link" }); }

                        
                      



                        <li class="nav-item">
                            @if (Session["username"] == null)
                            {
                                <a class="nav-link btn" style="background-color:#f6f6f6" href="/Kullanici/KayitOl">Kayıt Ol</a>

                            }
                            else
                            {
                                <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" href="">İşlemler</a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li class="nav-item nav-link">
                                        @Html.ActionLink("Yazı Oluştur", "Create", "Post", new { area = "" }, new { @class = "nav-link" })

                                        @Html.ActionLink("Yazılarım", "Yazilarim", "Post", new { area = "" }, new { @class = "nav-link" })
                                    </li>
                                </ul>
                            }
                        </li>
                        <li class="nav-item ">
                            @if (Session["username"] == null)
                            {
                                <a class="nav-link btn" style="background-color:#f6f6f6" href="/Kullanici/GirisYap">Giriş Yap</a>
                            }
                            else
                            {
                                <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" href="">@Session["username"].ToString()</a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li class="nav-item nav-link">
                                        @Html.ActionLink("Çıkış Yap", "CikisYap", "Kullanici", new { area = "" }, new { @class = "nav-link" })
                                    </li>
                                </ul>
                            }
                        </li>
                        <li class="nav-item dropdown submenu">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" href="/Home/Index">TR</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li class="nav-item">
                                    <a class="nav-link" href="home-EN.html">EN</a>
                                </li>
                            </ul>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    @RenderBody()



    <footer>
        <div class="container">
            <div class="copyright-text">
                <p>
                    &copy; @DateTime.Now.Year - Sakarya MYO İnternet Programcılığı Dersi- Uygulama Projesi
                </p>
            </div>
            <div>
                <ul class="social-icons">
                    <li><a href="#" target="_blank"><i class="fa fa-facebook"></i></a></li>
                    <li><a href="#" target="_blank"><i class="fa fa-twitter"></i></a></li>
                    <li><a href="#" target="_blank"><i class="fa fa-linkedin"></i></a></li>
                    <li><a href="#" target="_blank"><i class="fa fa-youtube-play"></i></a></li>
                </ul>
            </div>
        </div>
    </footer>


    <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>
    <!-- Bootstrap core JavaScript -->
    <script src="~/Content/vendor/jquery/jquery.min.js"></script>
    <script src="~/Content/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Additional Scripts -->
    @RenderSection("scripts", required: false)
    <script src="~/Content/assets/js/custom.js"></script>
    <script src="~/Content/assets/js/owl.js"></script>
    <script src="~/Content/assets/js/isotope.js"></script>
    <script src="~/Content/assets/js/slick.js"></script>
    <script src="~/Content/assets/js/accordions.js"></script>
    <script>
       $(document).ready(function () {
            $(window).scroll(function () {
                if ($(this).scrollTop() > 100) {
                    $('.back-to-top').fadeIn();
                } else {
                    $('.back-to-top').fadeOut();
                }
            });

            $('.back-to-top').click(function () {
                $("html, body").animate({
                    scrollTop: 0
                }, 600);
                return false;
            });

        });
    </script>

    <script language="text/Javascript">

      cleared[0] = cleared[1] = cleared[2] = 0; //set a cleared flag for each field
      function clearField(t){                   //declaring the array outside of the
      if(! cleared[t.id]){                      // function makes it static and global
          cleared[t.id] = 1;  // you could use true and false, but that's more typing
          t.value='';         // with more chance of typos
          t.style.color='#fff';
          }
      }
    </script>
</body>
</html>